# Generated by Django 5.0.6 on 2024-06-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='телеграм id'),
        ),
    ]
